[[plugins]]
repo = 'tyru/caw.vim'
on_path = '.*'
hook_add = '''
    nmap <Leader>c <Plug>(caw:hatpos:toggle)
    vmap <Leader>c <Plug>(caw:hatpos:toggle)
    nmap <Leader>C <Plug>(caw:wrap:comment)
    vmap <Leader>C <Plug>(caw:wrap:comment)
'''

[[plugins]]
repo = 'shougo/denite.nvim'
on_cmd = 'Denite'
depends = 'neomru.vim'
on_event = 'BufRead'
hook_source = 'source $XDG_CONFIG_HOME/nvim/plugins/denite.vim'

[[plugins]]
repo = 'shougo/neomru.vim'
on_path = ".*"

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_event = 'InsertEnter'

[[plugins]]
repo = 'cespare/vim-toml'
on_path = '.toml'

[[plugins]]
repo = 'deton/jasegment.vim'
on_path = '.*'

[[plugins]]
repo = 'thinca/vim-template'
on_path = '.*'

[[plugins]]
repo = 'thinca/vim-quickrun'
on_path = '.*'
hook_add = 'source ~/.config/nvim/plugins/vim-quickrun.vim'

[[plugins]]
repo = 'cocopon/colorswatch.vim'
on_cmd = 'ColorSwatchGenerate'

[[plugins]]
repo = 'iwataka/gitignore.vim'
on_cmd = ['Gitignore', 'GitignoreUpdate']

